version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  clean-api:
    container_name: clean-api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    ports:
      - "5050:5050"
    links:
      - mongo